name: Next Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/harold.com
          sudo apt update
          sudo apt upgrade
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          source ~/.bashrc
          nvm install 14
          nvm use 14
          git fetch origin
          git checkout production
          git pull
          npm install
          npm run build
          pm2 reload harold.com.vn
            
          
